

services:
  front:
    container_name: front
    build: 
      context: ./front/
      dockerfile: Dockerfile
      args:
        # BACKEND_URL: http://localhost:3000/
        BACKEND_URL: /api/

    # restart: always
    # ports:
    #   - 5000:80
    expose:
      - 80
    networks:
      - full_app_network

  api:
    # container_name: api
    build: 
      context: ./server/
      dockerfile: Dockerfile
    # restart: unless-stopped 
    # ports:
    #   - 3000:3000
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    networks:
      - full_app_network

  rev_proxy:
    image: nginx:alpine
    container_name: rev_proxy
    ports:
      - 80:80
      - 443:443

    environment:
      - NGINX_HOST=localhost
    volumes:
      - ./nginx/reverse_proxy/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      # # activate for ssl
      # - ./nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      # - ./nginx/ssl/localhost.key:/etc/ssl/private/localhost.key:ro
    depends_on:
      - api
      - front
    networks:
      - full_app_network

networks:
  full_app_network:
    driver: bridge
    

