

services:
  front:
    container_name: front
    build: 
      context: ./front/
      dockerfile: Dockerfile
      args:
        # BACKEND_URL: http://localhost:3000/
        BACKEND_URL: /api/

    # restart: always
    ports:
      - 5000:80
    networks:
      - full_app_network

  api:
    container_name: api
    build: 
      context: ./server/
      dockerfile: Dockerfile
    # restart: unless-stopped 
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    networks:
      - full_app_network

  rev_proxy:
    image: nginx:alpine
    container_name: rev_proxy
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx/reverse_proxy/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - api
      - front
    networks:
      - full_app_network

networks:
  full_app_network:
    driver: bridge
    

