

services:
  front:
    container_name: front
    build: 
      context: ./front/
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:3000/

    # restart: always
    ports:
      - 5000:80

    networks:
      - full_app_network

  api:
    container_name: api
    build: 
      context: ./server/
      dockerfile: Dockerfile
    # restart: unless-stopped 
    ports:
      - 3000:3000
    networks:
      - full_app_network



networks:
  full_app_network:
    driver: bridge
    

