apiVersion: v1
kind: Secret
metadata:
  name: notes-app-secrets
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: pass_pass
  # DATABASE_URL: "postgresql://postgres:pass_pass@notes_db:5432/notes_app?schema=public"      