apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
      - name: notes-backend
        image: notes-back:v1
        imagePullPolicy: IfNotPresent
        # envFrom:
        #   - secretRef:
        #       name: notes-app-secrets
        #   - configMapRef:
        #       name: notes-app-config
        env:
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: notes-app-config
                key: DB_NAME

          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: notes-app-config
                key: DB_PORT

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: notes-app-secrets
                key: DB_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notes-app-secrets
                key: DB_PASSWORD

          - name: DATABASE_URL
            value: "postgresql://postgres:$(DB_PASSWORD)@notes-db-svc:5432/$(DB_NAME)?schema=public"  

          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: notes-app-config
                key: NODE_ENV

        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend-svc
spec:
  type: ClusterIP
  selector:
    app: notes-backend
  ports:
  - port: 3000    
    targetPort: 3000

