apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-app-rev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notes-front-svc
                port:
                  number: 5000


          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notes-backend-svc
                port:
                  number: 3000     

    - host: notes.local
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notes-front-svc
                port:
                  number: 5000


          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notes-backend-svc
                port:
                  number: 3000       
                             
